script:
- |
  git config user.name "lc-education-ci"
  git config user.email "education+ci@launchcode.org"
  git remote remove origin
  git remote add origin https://$GITHUB_API_KEY@github.com/LaunchCodeEducation/liftoff-wiki.git > /dev/null 2>&1
  git remote add upstream https://$GITHUB_API_KEY@github.com/LaunchCodeEducation/liftoff.wiki.git > /dev/null 2>&1
  git fetch origin
  git fetch upstream
  git merge upstream/master --no-edit
  git push origin HEAD:master > /dev/null 2>&1
  git push upstream HEAD:master > /dev/null 2>&1
env:
  matrix:
    secure: c3xhACTPXf+MyL+KtRtnEBi9UTQnAFbADE/r0aUcPv3QNJJoAjJ7290ial+yqyT4vBOixl1gdz+w8pfc1FSzbtklEZ1vgZUdLGOybN9EGPw17eAyKq0RurudYDZIqR0tAV1/6qKtMBOqJ+NK/YGbIoH4ZDCnOOCXreGF036cgPKLPjmtRFy0S8f8rrGS/IIf5tqsu6HN3foph/nUiZ3CyCjvZVoLIcGPctUUmnVolqPwehcCmBRuusbNZhJmrrxeAHdJyUEvDRGuTMYAw4hMbLvq7OPWlB+pIzMCRQU+sryAtmfd4yxPG+FCgp4fbROA5X+q1JoYFglbEChS+ZD2+IYXvVpfO/5OkoEVxtUg/Zk+GRxK+p6osyhdCimbUII42ew4Uhs8j1+yfC3gPr7EDuGVL5AamAkcqbIacmZiAJhiaExPi3r4yDbgKR0Q9ki92ri6p41omU1Apmo7GfL+ZiEve8qhI6m9BZURQ+ZPeJf4EC63w4b+O3auxEoHSactIMOFVlgysSXu36r9zu0b+gM6WSDlu3k6oRI7qyOOlnBg/o+pl4CoAbYLsn1eNmRUK84tiZsgukYuvfHkdzPUuq32LHQ+rmnErOV6ZDCvLFJwbLvFA7NPihO3BJKAHn3P1gC6Nbc+vYin8POf0Mw0coPFA4YYGRzii7JWJhBPRH4=
